
# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту maxim1994barca@gmail.com(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -maxim1994barca@gmail.com
    on_success: never # default: change
    on_failure: always # default: always


    env:
      global:
        - CODECOV_TOKEN="d82c4a5c-59c4-4184-9a65-8201005be979"
